import os

FOLKRNN_MAX_SEED = 1000000

# conforming abc

ABC2ABC_PATH = '/usr/bin/abc2abc'

# folk_rnn task

FOLKRNN_INSTANCE_CACHE_COUNT = 2

STORE_PATH = '/var/opt/folk_rnn_task'
MODEL_PATH = os.path.join(STORE_PATH, 'models')
TUNE_PATH = os.path.join(STORE_PATH, 'tunes')

FOLKRNN_TUNE_TITLE = None
FOLKRNN_TUNE_TITLE_CLIENT = 'Folk RNN Tune №'

try:
    os.makedirs(MODEL_PATH)
except OSError:
    pass

try:
    os.makedirs(TUNE_PATH)
except OSError:
    pass

# import here as rnn_models imports above constants
from .rnn_models import models_json
static_path = os.path.join(os.path.dirname(__file__), 'static')
with open(os.path.join(static_path, 'folk_rnn_models.js'), 'w') as f:
    js =  '// Auto-generated by composer package \n'
    js += '// See __init__.py, rnn_models.py \n'
    js += ' \n'
    js += 'if (typeof folkrnn == "undefined") \n'
    js += '    folkrnn = {}; \n'
    js += ' \n'
    js += f'folkrnn.tuneTitle = "{FOLKRNN_TUNE_TITLE_CLIENT}"; \n'
    js += f'folkrnn.maxSeed = {FOLKRNN_MAX_SEED}; \n'
    js += 'folkrnn.models = ' + models_json() + '; \n'
    f.write(js)
    