import os

# conforming abc

ABC2ABC_PATH = '/usr/bin/abc2abc'

# folk_rnn task

FOLKRNN_INSTANCE_CACHE_COUNT = 2

STORE_PATH = '/var/opt/folk_rnn_task'
MODEL_PATH = os.path.join(STORE_PATH, 'models')
TUNE_PATH = os.path.join(STORE_PATH, 'tunes')

try:
    os.makedirs(MODEL_PATH)
except OSError:
    pass

try:
    os.makedirs(TUNE_PATH)
except OSError:
    pass

# import here as rnn_models imports above constants
from .rnn_models import models_json
static_path = os.path.join(os.path.dirname(__file__), 'static')
with open(os.path.join(static_path, 'folk_rnn_models.js'), 'w') as f:
    js = '''// Auto-generated by composer package 
// See __init__.py, rnn_models.py

var rnnModels = ''' + models_json() + ';'
    f.write(js)
    