# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0002_tune_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tune',
            name='rnn_finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tune',
            name='rnn_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tune',
            name='rnn_tune',
            field=models.TextField(default=''),
        ),
    ]
