# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0003_auto_20171102_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='rnn_model_name',
            field=models.CharField(default='test_model.pickle_2', max_length=64),
        ),
    ]
