# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0004_tune_rnn_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tune',
            old_name='seed',
            new_name='prime_tokens',
        ),
        migrations.AlterField(
            model_name='tune',
            name='rnn_model_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
