# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0005_auto_20171115_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='seed',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='tune',
            name='temp',
            field=models.FloatField(default=1.0),
        ),
    ]
