# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0008_auto_20171204_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='composer.CandidateTune')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('author', models.CharField(default='', max_length=128)),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composer.ArchiveTune')),
            ],
        ),
    ]
