# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0009_archivetune_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivetune',
            name='tune',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='archivetune',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composer.CandidateTune'),
        ),
    ]
