# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0010_auto_20171204_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
