# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0012_comment_submitted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchiveTune',
            new_name='Setting',
        ),
        migrations.RenameModel(
            old_name='CandidateTune',
            new_name='Tune',
        ),
    ]
