# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0013_auto_20171212_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tune',
            old_name='rnn_tune',
            new_name='abc_rnn',
        ),
        migrations.RenameField(
            model_name='tune',
            old_name='user_tune',
            new_name='abc_user',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='candidate',
        ),
        migrations.AddField(
            model_name='setting',
            name='abc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composer.Tune'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composer.Tune'),
        ),
    ]
