# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0014_auto_20171212_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNNTune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnn_model_name', models.CharField(default='', max_length=64)),
                ('seed', models.IntegerField(default=42)),
                ('temp', models.FloatField(default=1.0)),
                ('prime_tokens', models.TextField(default='')),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('rnn_started', models.DateTimeField(null=True)),
                ('rnn_finished', models.DateTimeField(null=True)),
                ('abc', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tune',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='tune',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='Tune',
        ),
    ]
