# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0015_auto_20180130_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rnntune',
            old_name='prime_tokens',
            new_name='start_abc',
        ),
        migrations.AddField(
            model_name='rnntune',
            name='key',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='rnntune',
            name='meter',
            field=models.CharField(default='', max_length=6),
        ),
    ]
