# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0018_auto_20181126_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnntune',
            name='unitnotelength',
            field=models.CharField(default='', max_length=7),
        ),
    ]
