# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composer', '0015_auto_20180130_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('author', models.CharField(default='', max_length=128)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_rnn', models.TextField(default='')),
                ('abc_user', models.TextField(default='')),
                ('rnn_tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composer.RNNTune')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='setting',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Tune'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Tune'),
        ),
    ]
