# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuneAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tune',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tune',
            name='rnn_tune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='composer.RNNTune'),
        ),
        migrations.AddField(
            model_name='tuneattribution',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Tune'),
        ),
    ]
