# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0002_auto_20180517_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('body', models.TextField()),
                ('url', models.URLField()),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('body', models.TextField()),
                ('url', models.URLField()),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuneEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Event')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Tune')),
            ],
        ),
        migrations.CreateModel(
            name='TuneRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Recording')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Tune')),
            ],
        ),
    ]
