# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0005_recording_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
