# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0006_auto_20180517_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tune',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tuneattribution',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tuneevent',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tunerecording',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='tune',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
