# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0007_auto_20180528_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuneevent',
            options={'ordering': ['tune']},
        ),
        migrations.AlterModelOptions(
            name='tunerecording',
            options={'ordering': ['tune']},
        ),
    ]
