# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0009_tunebookentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='check_valid_abc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tune',
            name='check_valid_abc',
            field=models.BooleanField(default=True),
        ),
    ]
