# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0011_tbz_comment_to_tunecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunecomment',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
