# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-19 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0012_auto_20180718_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(help_text='This is a markdown field, e.g. *italics* and [a link](http://tobyz.net)')),
                ('tune_vote_open', models.DateField()),
                ('tune_vote_close', models.DateField()),
                ('recording_vote_open', models.DateField()),
                ('recording_vote_close', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', related_query_name='comment', to='archiver.Competition')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionTune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Competition')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Tune')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tunecomment',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', related_query_name='comment', to='archiver.Tune'),
        ),
        migrations.CreateModel(
            name='CompetitionRecordingVote',
            fields=[
                ('votemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archiver.VoteModel')),
            ],
            bases=('archiver.votemodel',),
        ),
        migrations.CreateModel(
            name='CompetitionTuneVote',
            fields=[
                ('votemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archiver.VoteModel')),
                ('votable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', related_query_name='vote', to='archiver.CompetitionTune')),
            ],
            bases=('archiver.votemodel',),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionrecording',
            name='competition_tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.CompetitionTune'),
        ),
        migrations.AddField(
            model_name='competitionrecording',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Recording'),
        ),
        migrations.AddField(
            model_name='competitionrecordingvote',
            name='votable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', related_query_name='vote', to='archiver.CompetitionRecording'),
        ),
    ]
