# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-20 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0013_auto_20180719_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='tune_vote_close',
            new_name='recording_submit_open',
        ),
    ]
