# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    TunebookEntry = apps.get_model("archiver", "TunebookEntry")
    Collection = apps.get_model("archiver", "Collection")
    CollectionEntry = apps.get_model("archiver", "CollectionEntry")
    entries = TunebookEntry.objects.all()
    for tunebookentry in entries:
        tunebook, created = Collection.objects.get_or_create(user=tunebookentry.user)
        collectionentry = CollectionEntry(
            id = tunebookentry.id,
            tune = tunebookentry.tune,
            setting = tunebookentry.setting,
            collection = tunebook,
            submitted = tunebookentry.submitted,
            )
        collectionentry.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0014_auto_20180722_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.Collection')),
                ('setting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archiver.Setting')),
                ('tune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archiver.Tune')),
            ],
        ),
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='tunebookentry',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='tunebookentry',
            name='tune',
        ),
        migrations.RemoveField(
            model_name='tunebookentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='TunebookEntry',
        ),
    ]
